### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by Daksh777**

### CODE REVIEW

**Comment by c0re100** [comment]
Thank you for correct my grammar mistakes.😁
But I have something to say.
1. `Enhanced Setting` change to `Enhanced Settings`.
Cause `TDesktop-x64` will be rename to `Telegram Enhanced`(possibly), but I have no idea when it will come.
2. `Disable cloud draft sync` change to `Disable cloud draft sync to local`.
Cloud draft feature is still active in tdesktop x64.
Client is ignore any changes from cloud, but client is still syncing `local draft` to cloud for another device.

**Comment by Daksh777** [comment]
1. Done
2. "Disable cloud draft sync to local" doesn't make sense and causes confusion. However, "Disable draft sync for local device" would be self-explanatory and sound better. So, tell me if you'd like me to change it to that.

**Comment by c0re100** [comment]
> 1. Done
> 2. "Disable cloud draft sync to local" doesn't make sense and causes confusion. However, "Disable draft sync for local device" would be self-explanatory and sound better. So, tell me if you'd like me to change it to that or keep it as it is.

How about `Stop syncing draft from cloud`?

**Comment by Daksh777** [comment]
That would be great. I'll make the changes.

**Comment by c0re100** [comment]
Thank you~

**Pull request merged**
